In [ ]:
#clean food data set
import pandas as pd
df = pd.read_csv("StateAndCountyData.csv", header=None,
                 names=["FIPS", "State", "County", "Variable", "Value"],
                 dtype={"FIPS": str})
df_ca = df[df["State"] == "CA"]
variables = ["PCT_LACCESS_POP19", "PCT_LACCESS_LOWI19", "PCT_LACCESS_HHNV19",
             "GROCPTH20", "SUPERCPTH20", "SNAPSPTH23",
             "CONVSPTH20", "FFRPTH20", "MEDHHINC21"]
df_ca_filtered = df_ca[df_ca["Variable"].isin(variables)]
df_food = df_ca_filtered.pivot(index=["FIPS", "County"],
                                columns="Variable",
                                values="Value").reset_index()
df_food.columns.name = None
df_food[variables] = df_food[variables].astype(float)
df_food = df_food.sort_values("County").reset_index(drop=True)
df_food

/tmp/ipykernel_514/1592960392.py:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("StateAndCountyData.csv", header=None,

,FIPS,County,CONVSPTH20,FFRPTH20,GROCPTH20,MEDHHINC21,PCT_LACCESS_HHNV19,PCT_LACCESS_LOWI19,PCT_LACCESS_POP19,SNAPSPTH23,SUPERCPTH20
0,06001,Alameda,0.197314,0.827156,0.219572,108971.0,0.342808,1.117399,8.083675,0.545731,0.016242
1,06003,Alpine,-9999.000000,2.680965,-9999.000000,87570.0,6.022490,16.785139,56.969242,-9999.000000,-9999.000000
2,06005,Amador,0.324327,0.573809,0.299379,68159.0,3.163143,0.095632,0.174187,0.763980,-9999.000000
3,06007,Butte,0.329034,0.737976,0.188019,62982.0,1.979342,6.450867,19.113434,0.926945,0.018802
4,06009,Calaveras,0.410296,0.604647,0.259135,68298.0,1.547478,5.989503,14.736117,0.985243,-9999.000000
5,06011,Colusa,0.556638,0.417478,0.324705,60725.0,2.258987,12.356255,39.329746,1.283756,-9999.000000
6,06013,Contra Costa,0.200463,0.678623,0.194388,110595.0,0.766959,2.867471,23.228312,0.542727,0.013885
7,06015,Del Norte,0.178776,0.321796,0.143021,48108.0,3.967303,14.445117,34.407192,0.983177,-9999.000000
8,06017,El Dorado,0.285085,0.673837,0.171051,87689.0,1.906889,4.258567,25.222891,0.636368,0.020733
9,06019,Fresno,0.298726,0.731329,0.252768,63140.0,0.889459,5.349311,13.327069,0.916412,0.019982
10,06021,Glenn,0.388926,0.671782,0.212142,56741.0,2.142960,8.745303,23.445011,1.256238,-9999.000000
11,06023,Humboldt,0.422294,0.622328,0.296347,53924.0,1.848892,4.540260,11.186273,1.072488,0.029635
12,06025,Imperial,0.410502,0.610206,0.138683,50970.0,1.431648,7.648736,17.641117,0.729488,0.027737
13,06027,Inyo,0.831209,0.997451,0.221656,62381.0,1.883897,7.771645,28.887903,1.168410,-9999.000000
14,06029,Kern,0.306203,0.726678,0.211902,57926.0,1.337915,7.829901,23.772337,0.860089,0.017751
15,06031,Kings,0.340555,0.674561,0.255416,60810.0,1.055195,6.822826,33.028690,0.767138,0.019647
16,06033,Lake,0.480777,0.542812,0.372214,55801.0,2.951067,1.889676,4.177565,1.058450,-9999.000000
17,06035,Lassen,0.433102,0.533049,0.233209,56923.0,1.978429,9.301450,31.891712,1.035359,-9999.000000
18,06037,Los Angeles,0.216232,0.879006,0.191893,77356.0,0.230622,1.452951,6.531888,0.633611,0.016092
19,06039,Madera,0.373983,0.507096,0.171145,60241.0,2.185023,5.418890,14.494282,0.966657,-9999.000000
20,06041,Marin,0.190416,0.773320,0.291452,118472.0,0.366653,1.165825,11.887547,0.456840,0.015544
21,06043,Mariposa,0.174825,0.349650,0.291375,60377.0,2.170580,2.611354,8.073803,0.817280,-9999.000000
22,06045,Mendocino,0.476406,0.720419,0.476406,57516.0,1.994999,5.922134,14.481230,1.108124,-9999.000000
23,06047,Merced,0.272156,0.529987,0.196955,54703.0,1.438985,7.711543,18.937424,0.921039,0.025067
24,06049,Modoc,0.342349,-9999.000000,0.570581,49273.0,0.848351,17.175961,40.543320,1.618310,-9999.000000
25,06051,Mono,0.550433,1.651300,0.412825,70945.0,1.467635,17.237467,57.093903,0.680838,-9999.000000
26,06053,Monterey,0.297049,0.666039,0.280804,81404.0,0.648934,5.080918,16.629837,0.664977,0.018566
27,06055,Napa,0.338322,0.566322,0.272129,94127.0,0.910559,2.629963,12.084171,0.524078,0.029419
28,06057,Nevada,0.281108,0.622452,0.291147,77220.0,1.389410,8.613041,34.762379,0.674342,-9999.000000
29,06059,Orange,0.222618,0.970047,0.160727,100210.0,0.262204,1.121259,8.671787,0.483745,0.023683
30,06061,Placer,0.307730,0.878521,0.161310,103588.0,1.167848,5.106532,31.929096,0.543521,0.024817
31,06063,Plumas,0.579955,0.579955,0.579955,58154.0,1.802116,1.071077,6.298171,1.272265,-9999.000000
32,06065,Riverside,0.217340,0.696211,0.141813,78690.0,0.990094,6.965470,24.481379,0.555261,0.018480
33,06067,Sacramento,0.243723,0.772218,0.188565,79611.0,0.658604,4.226967,16.813540,0.686419,0.021807
34,06069,San Benito,0.234174,0.515182,0.140504,95187.0,0.896890,2.696964,17.873438,0.370639,-9999.000000
35,06071,San Bernardino,0.252149,0.773348,0.140692,74218.0,1.342740,8.528562,24.656145,0.692940,0.018272
36,06073,San Diego,0.223561,0.853432,0.173147,90756.0,0.476854,2.763061,14.927285,0.541995,0.019505
37,06075,San Francisco,0.129240,1.152773,0.400413,119776.0,0.114791,0.302544,0.584508,0.627470,0.010385
38,06077,San Joaquin,0.260428,0.658882,0.239594,79598.0,0.871344,4.535321,14.412910,0.762081,0.019532
39,06079,San Luis Obispo,0.294067,0.924715,0.212578,79688.0,1.019286,4.054190,18.622091,0.653149,0.017715
40,06081,San Mateo,0.195171,0.767498,0.238689,131151.0,0.361650,0.919327,10.517214,0.405701,0.097586
41,06083,Santa Barbara,0.233831,0.847637,0.278798,83185.0,0.541791,2.881691,12.243940,0.597467,0.015739
42,06085,Santa Clara,0.191390,0.798068,0.175135,141161.0,0.298099,0.966271,8.487587,0.426224,0.018352
43,06087,Santa Cruz,0.218579,0.696490,0.240808,90370.0,0.974291,5.418862,22.582853,0.592022,0.014819
44,06089,Shasta,0.441274,0.714976,0.229016,60187.0,2.143146,6.916362,20.261036,1.000814,0.022343
45,06091,Sierra,1.027397,-9999.000000,-9999.000000,60659.0,4.103383,24.821465,88.249901,1.028807,-9999.000000
46,06093,Siskiyou,0.578102,0.716846,0.323737,50069.0,2.898830,11.382891,28.644606,1.634543,-9999.000000
47,06095,Solano,0.295345,0.660051,0.163335,87348.0,0.626808,3.780611,21.658522,0.596459,0.024612
48,06097,Sonoma,0.293986,0.645136,0.287861,92999.0,0.805661,2.581933,13.296393,0.692005,0.016333
49,06099,Stanislaus,0.332678,0.707169,0.225421,73151.0,0.743791,3.369372,9.670941,0.880334,0.021815
50,06101,Sutter,0.466878,0.664004,0.228251,63246.0,1.514784,8.136843,26.482990,0.918255,0.031125
51,06103,Tehama,0.465160,0.511675,0.155053,53654.0,3.360351,9.966781,19.090176,1.145318,-9999.000000
52,06105,Trinity,0.818599,0.491159,0.573019,45508.0,3.641630,7.665814,17.603451,1.510479,-9999.000000
53,06107,Tulare,0.373389,0.614492,0.238969,57398.0,1.072866,4.916412,11.175652,0.950478,0.021337
54,06109,Tuolumne,0.311841,0.476933,0.275154,61396.0,2.686450,6.160719,27.833937,0.763734,-9999.000000
55,06111,Ventura,0.222252,0.772534,0.207990,95819.0,0.526427,2.309816,14.892350,0.564127,0.019016
56,06113,Yolo,0.236656,0.709969,0.186594,76247.0,0.463608,2.884491,13.680482,0.741454,0.027306
57,06115,Yuba,0.311876,0.399202,0.149701,60764.0,2.630084,10.882041,21.463261,1.015850,-9999.000000

In [ ]:
#clean health data set
file = "CountyHealthRankings.xlsx"
df_rank = pd.read_excel(
    file,
    sheet_name="Ranked Measure Data",
    header=1
)
df_add = pd.read_excel(
    file,
    sheet_name="Additional Measure Data",
    header=1
)
df_obesity = df_rank[["FIPS", "County", "% Adults with Obesity"]]
df_diabetes = df_add[["FIPS", "County", "% Adults with Diabetes"]]
df_obesity["FIPS"] = df_obesity["FIPS"].astype(str).str.zfill(5)
df_diabetes["FIPS"] = df_diabetes["FIPS"].astype(str).str.zfill(5)
df_health = pd.merge(
    df_obesity,
    df_diabetes[["FIPS", "% Adults with Diabetes"]],
    on="FIPS",
    how="inner")
df_health

/tmp/ipykernel_514/538965661.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_obesity["FIPS"] = df_obesity["FIPS"].astype(str).str.zfill(5)
/tmp/ipykernel_514/538965661.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_diabetes["FIPS"] = df_diabetes["FIPS"].astype(str).str.zfill(5)

     FIPS           County  % Adults with Obesity  % Adults with Diabetes
0   06000              NaN                   26.2                     9.4
1   06001          Alameda                   23.5                     9.1
2   06003           Alpine                   29.9                     9.9
3   06005           Amador                   29.4                     9.0
4   06007            Butte                   31.7                     9.5
5   06009        Calaveras                   30.1                     8.7
6   06011           Colusa                   32.3                    11.8
7   06013     Contra Costa                   23.9                     9.4
8   06015        Del Norte                   33.4                    10.9
9   06017        El Dorado                   26.0                     7.9
10  06019           Fresno                   37.6                    13.5
11  06021            Glenn                   32.3                    11.6
12  06023         Humboldt                   28.0                     9.5
13  06025         Imperial                   35.9                    14.6
14  06027             Inyo                   28.0                     9.2
15  06029             Kern                   35.5                    13.0
16  06031            Kings                   35.3                    12.9
17  06033             Lake                   32.3                    10.5
18  06035           Lassen                   30.6                    10.3
19  06037      Los Angeles                   27.8                    11.1
20  06039           Madera                   32.7                    12.7
21  06041            Marin                   22.5                     7.1
22  06043         Mariposa                   27.7                     9.0
23  06045        Mendocino                   30.8                    10.0
24  06047           Merced                   34.6                    13.2
25  06049            Modoc                   31.2                    10.2
26  06051             Mono                   29.0                     9.1
27  06053         Monterey                   32.1                    11.6
28  06055             Napa                   28.6                     9.1
29  06057           Nevada                   25.1                     7.8
30  06059           Orange                   24.5                    10.2
31  06061           Placer                   24.6                     7.6
32  06063           Plumas                   28.9                     8.3
33  06065        Riverside                   33.4                    11.1
34  06067       Sacramento                   27.8                    10.3
35  06069       San Benito                   30.1                    10.9
36  06071   San Bernardino                   33.3                    11.9
37  06073        San Diego                   24.1                     9.4
38  06075    San Francisco                   16.4                     9.0
39  06077      San Joaquin                   31.9                    11.5
40  06079  San Luis Obispo                   26.2                     8.7
41  06081        San Mateo                   20.6                     8.7
42  06083    Santa Barbara                   27.3                    10.3
43  06085      Santa Clara                   21.3                     9.0
44  06087       Santa Cruz                   29.3                     9.4
45  06089           Shasta                   27.8                     8.9
46  06091           Sierra                   29.6                     9.3
47  06093         Siskiyou                   31.3                     9.7
48  06095           Solano                   30.7                    10.0
49  06097           Sonoma                   27.1                     8.2
50  06099       Stanislaus                   30.8                    11.8
51  06101           Sutter                   29.1                    11.2
52  06103           Tehama                   35.1                    11.1
53  06105          Trinity                   30.0                     9.8
54  06107           Tulare                   35.7                    13.9
55  06109         Tuolumne                   28.0                     8.9
56  06111          Ventura                   27.5                     9.6
57  06113             Yolo                   29.9                    10.4
58  06115             Yuba                   31.3                    10.6

In [ ]:
df_cancer = pd.read_csv("cali_cancer_rates.csv", skiprows=8)
df_cancer = df_cancer.iloc[2:60]
df_cancer = df_cancer[[
    "County",
    "FIPS",
    "Age-Adjusted Incidence Rate([rate note]) - cases per 100,000"]]
df_cancer["County"] = (
    df_cancer["County"]
    .str.replace(" County", "", regex=False)   # remove " County"
    .str.replace(r"\(.*\)", "", regex=True)    # remove "(7)" etc
    .str.strip())
df_cancer = df_cancer.rename(columns={
    "Age-Adjusted Incidence Rate([rate note]) - cases per 100,000": "Cancer Incidence Rate"})
df_cancer["Cancer Incidence Rate"] = pd.to_numeric(df_cancer["Cancer Incidence Rate"], errors="coerce")
df_cancer

             County    FIPS  Cancer Incidence Rate
2             Butte  6007.0                   42.5
3        San Benito  6069.0                   40.3
4            Colusa  6011.0                   40.1
5            Tehama  6103.0                   39.8
6              Lake  6033.0                   39.6
7            Merced  6047.0                   39.4
8            Amador  6005.0                   39.3
9              Yuba  6115.0                   38.9
10        Calaveras  6009.0                   38.4
11           Shasta  6089.0                   37.9
12       Santa Cruz  6087.0                   37.7
13      San Joaquin  6077.0                   37.2
14           Sonoma  6097.0                   36.9
15            Modoc  6049.0                   36.8
16         Humboldt  6023.0                   36.4
17             Kern  6029.0                   36.1
18   San Bernardino  6071.0                   36.0
19        El Dorado  6017.0                   35.6
20           Madera  6039.0                   35.6
21       Stanislaus  6099.0                   35.6
22       Sacramento  6067.0                   35.5
23           Solano  6095.0                   35.5
24             Napa  6055.0                   35.4
25        Mendocino  6045.0                   35.3
26        Riverside  6065.0                   35.0
27         Imperial  6025.0                   34.8
28            Glenn  6021.0                   34.8
29      Los Angeles  6037.0                   34.7
30          Ventura  6111.0                   34.7
31     Contra Costa  6013.0                   34.2
32        San Diego  6073.0                   34.2
33    Santa Barbara  6083.0                   34.2
34         Mariposa  6043.0                   34.0
35           Sutter  6101.0                   34.0
36             Yolo  6113.0                   33.5
37  San Luis Obispo  6079.0                   33.3
38      Santa Clara  6085.0                   33.2
39           Fresno  6019.0                   33.1
40            Marin  6041.0                   33.1
41    San Francisco  6075.0                   32.3
42         Siskiyou  6093.0                   32.3
43           Placer  6061.0                   32.1
44           Tulare  6107.0                   32.1
45           Orange  6059.0                   32.0
46         Tuolumne  6109.0                   31.9
47          Alameda  6001.0                   31.7
48             Mono  6051.0                   31.2
49             Inyo  6027.0                   30.7
50         Monterey  6053.0                   30.7
51           Lassen  6035.0                   30.5
52        San Mateo  6081.0                   30.4
53           Plumas  6063.0                   29.7
54            Kings  6031.0                   27.6
55           Nevada  6057.0                   24.6
56        Del Norte  6015.0                   24.5
57          Trinity  6105.0                   19.9
58           Alpine  6003.0                    NaN
59           Sierra  6091.0                    NaN

In [ ]:
#merge
import numpy as np
df_final = pd.merge(df_food, df_health, on=["FIPS", "County"])
df_final = df_final.rename(columns={
    "PCT_LACCESS_POP19": "% Population with low access to store",
    "PCT_LACCESS_LOWI19": "% Population low income & low access to store",
    "PCT_LACCESS_HHNV19": "% Households, no car & low access to store",
    "GROCPTH20": "Grocery stores/1,000 population",
    "SUPERCPTH20": "Supercenters/1,000 population",
    "SNAPSPTH23": "SNAP-authorized stores/1,000 population",
    "FOODINSEC_21_23": "% Household food insecurity",
    "CONVSPTH20": "Convenience stores/1,000 population",
    "FFRPTH20": "Fast-food restaurants/1,000 population",
    "MEDHHINC21": "Median household income"
})
num_cols = df_final.select_dtypes(include='number')
df_final[num_cols.columns] = num_cols.mask(num_cols < 0)
df_final["Retail Food Environment Index"] = (
    (df_final["Fast-food restaurants/1,000 population"] +
     df_final["Convenience stores/1,000 population"])
    /
    (df_final["Grocery stores/1,000 population"] +
     df_final["Supercenters/1,000 population"])
)
df_final["FIPS"] = df_final["FIPS"].astype(int)
df_cancer["FIPS"] = df_cancer["FIPS"].astype(int)
df_final = pd.merge(df_final, df_cancer, on=["FIPS", "County"], how="left")
df_final

,FIPS,County,"Convenience stores/1,000 population","Fast-food restaurants/1,000 population","Grocery stores/1,000 population",Median household income,"% Households, no car & low access to store",% Population low income & low access to store,% Population with low access to store,"SNAP-authorized stores/1,000 population","Supercenters/1,000 population",% Adults with Obesity,% Adults with Diabetes,Retail Food Environment Index,Cancer Incidence Rate
0,6001,Alameda,0.197314,0.827156,0.219572,108971.0,0.342808,1.117399,8.083675,0.545731,0.016242,23.5,9.1,4.344388,31.7
1,6003,Alpine,NaN,2.680965,NaN,87570.0,6.022490,16.785139,56.969242,NaN,NaN,29.9,9.9,NaN,NaN
2,6005,Amador,0.324327,0.573809,0.299379,68159.0,3.163143,0.095632,0.174187,0.763980,NaN,29.4,9.0,NaN,39.3
3,6007,Butte,0.329034,0.737976,0.188019,62982.0,1.979342,6.450867,19.113434,0.926945,0.018802,31.7,9.5,5.159091,42.5
4,6009,Calaveras,0.410296,0.604647,0.259135,68298.0,1.547478,5.989503,14.736117,0.985243,NaN,30.1,8.7,NaN,38.4
5,6011,Colusa,0.556638,0.417478,0.324705,60725.0,2.258987,12.356255,39.329746,1.283756,NaN,32.3,11.8,NaN,40.1
6,6013,Contra Costa,0.200463,0.678623,0.194388,110595.0,0.766959,2.867471,23.228312,0.542727,0.013885,23.9,9.4,4.220833,34.2
7,6015,Del Norte,0.178776,0.321796,0.143021,48108.0,3.967303,14.445117,34.407192,0.983177,NaN,33.4,10.9,NaN,24.5
8,6017,El Dorado,0.285085,0.673837,0.171051,87689.0,1.906889,4.258567,25.222891,0.636368,0.020733,26.0,7.9,5.000000,35.6
9,6019,Fresno,0.298726,0.731329,0.252768,63140.0,0.889459,5.349311,13.327069,0.916412,0.019982,37.6,13.5,3.776557,33.1
10,6021,Glenn,0.388926,0.671782,0.212142,56741.0,2.142960,8.745303,23.445011,1.256238,NaN,32.3,11.6,NaN,34.8
11,6023,Humboldt,0.422294,0.622328,0.296347,53924.0,1.848892,4.540260,11.186273,1.072488,0.029635,28.0,9.5,3.204545,36.4
12,6025,Imperial,0.410502,0.610206,0.138683,50970.0,1.431648,7.648736,17.641117,0.729488,0.027737,35.9,14.6,6.133333,34.8
13,6027,Inyo,0.831209,0.997451,0.221656,62381.0,1.883897,7.771645,28.887903,1.168410,NaN,28.0,9.2,NaN,30.7
14,6029,Kern,0.306203,0.726678,0.211902,57926.0,1.337915,7.829901,23.772337,0.860089,0.017751,35.5,13.0,4.497585,36.1
15,6031,Kings,0.340555,0.674561,0.255416,60810.0,1.055195,6.822826,33.028690,0.767138,0.019647,35.3,12.9,3.690476,27.6
16,6033,Lake,0.480777,0.542812,0.372214,55801.0,2.951067,1.889676,4.177565,1.058450,NaN,32.3,10.5,NaN,39.6
17,6035,Lassen,0.433102,0.533049,0.233209,56923.0,1.978429,9.301450,31.891712,1.035359,NaN,30.6,10.3,NaN,30.5
18,6037,Los Angeles,0.216232,0.879006,0.191893,77356.0,0.230622,1.452951,6.531888,0.633611,0.016092,27.8,11.1,5.265957,34.7
19,6039,Madera,0.373983,0.507096,0.171145,60241.0,2.185023,5.418890,14.494282,0.966657,NaN,32.7,12.7,NaN,35.6
20,6041,Marin,0.190416,0.773320,0.291452,118472.0,0.366653,1.165825,11.887547,0.456840,0.015544,22.5,7.1,3.139241,33.1
21,6043,Mariposa,0.174825,0.349650,0.291375,60377.0,2.170580,2.611354,8.073803,0.817280,NaN,27.7,9.0,NaN,34.0
22,6045,Mendocino,0.476406,0.720419,0.476406,57516.0,1.994999,5.922134,14.481230,1.108124,NaN,30.8,10.0,NaN,35.3
23,6047,Merced,0.272156,0.529987,0.196955,54703.0,1.438985,7.711543,18.937424,0.921039,0.025067,34.6,13.2,3.612903,39.4
24,6049,Modoc,0.342349,NaN,0.570581,49273.0,0.848351,17.175961,40.543320,1.618310,NaN,31.2,10.2,NaN,36.8
25,6051,Mono,0.550433,1.651300,0.412825,70945.0,1.467635,17.237467,57.093903,0.680838,NaN,29.0,9.1,NaN,31.2
26,6053,Monterey,0.297049,0.666039,0.280804,81404.0,0.648934,5.080918,16.629837,0.664977,0.018566,32.1,11.6,3.217054,30.7
27,6055,Napa,0.338322,0.566322,0.272129,94127.0,0.910559,2.629963,12.084171,0.524078,0.029419,28.6,9.1,3.000000,35.4
28,6057,Nevada,0.281108,0.622452,0.291147,77220.0,1.389410,8.613041,34.762379,0.674342,NaN,25.1,7.8,NaN,24.6
29,6059,Orange,0.222618,0.970047,0.160727,100210.0,0.262204,1.121259,8.671787,0.483745,0.023683,24.5,10.2,6.467465,32.0
30,6061,Placer,0.307730,0.878521,0.161310,103588.0,1.167848,5.106532,31.929096,0.543521,0.024817,24.6,7.6,6.373334,32.1
31,6063,Plumas,0.579955,0.579955,0.579955,58154.0,1.802116,1.071077,6.298171,1.272265,NaN,28.9,8.3,NaN,29.7
32,6065,Riverside,0.217340,0.696211,0.141813,78690.0,0.990094,6.965470,24.481379,0.555261,0.018480,33.4,11.1,5.699248,35.0
33,6067,Sacramento,0.243723,0.772218,0.188565,79611.0,0.658604,4.226967,16.813540,0.686419,0.021807,27.8,10.3,4.829268,35.5
34,6069,San Benito,0.234174,0.515182,0.140504,95187.0,0.896890,2.696964,17.873438,0.370639,NaN,30.1,10.9,NaN,40.3
35,6071,San Bernardino,0.252149,0.773348,0.140692,74218.0,1.342740,8.528562,24.656145,0.692940,0.018272,33.3,11.9,6.451149,36.0
36,6073,San Diego,0.223561,0.853432,0.173147,90756.0,0.476854,2.763061,14.927285,0.541995,0.019505,24.1,9.4,5.590343,34.2
37,6075,San Francisco,0.129240,1.152773,0.400413,119776.0,0.114791,0.302544,0.584508,0.627470,0.010385,16.4,9.0,3.120787,32.3
38,6077,San Joaquin,0.260428,0.658882,0.239594,79598.0,0.871344,4.535321,14.412910,0.762081,0.019532,31.9,11.5,3.547739,37.2
39,6079,San Luis Obispo,0.294067,0.924715,0.212578,79688.0,1.019286,4.054190,18.622091,0.653149,0.017715,26.2,8.7,5.292308,33.3
40,6081,San Mateo,0.195171,0.767498,0.238689,131151.0,0.361650,0.919327,10.517214,0.405701,0.097586,20.6,8.7,2.862745,30.4
41,6083,Santa Barbara,0.233831,0.847637,0.278798,83185.0,0.541791,2.881691,12.243940,0.597467,0.015739,27.3,10.3,3.671756,34.2
42,6085,Santa Clara,0.191390,0.798068,0.175135,141161.0,0.298099,0.966271,8.487587,0.426224,0.018352,21.3,9.0,5.113821,33.2
43,6087,Santa Cruz,0.218579,0.696490,0.240808,90370.0,0.974291,5.418862,22.582853,0.592022,0.014819,29.3,9.4,3.579710,37.7
44,6089,Shasta,0.441274,0.714976,0.229016,60187.0,2.143146,6.916362,20.261036,1.000814,0.022343,27.8,8.9,4.600000,37.9
45,6091,Sierra,1.027397,NaN,NaN,60659.0,4.103383,24.821465,88.249901,1.028807,NaN,29.6,9.3,NaN,NaN
46,6093,Siskiyou,0.578102,0.716846,0.323737,50069.0,2.898830,11.382891,28.644606,1.634543,NaN,31.3,9.7,NaN,32.3
47,6095,Solano,0.295345,0.660051,0.163335,87348.0,0.626808,3.780611,21.658522,0.596459,0.024612,30.7,10.0,5.083333,35.5
48,6097,Sonoma,0.293986,0.645136,0.287861,92999.0,0.805661,2.581933,13.296393,0.692005,0.016333,27.1,8.2,3.087248,36.9
49,6099,Stanislaus,0.332678,0.707169,0.225421,73151.0,0.743791,3.369372,9.670941,0.880334,0.021815,30.8,11.8,4.205882,35.6
50,6101,Sutter,0.466878,0.664004,0.228251,63246.0,1.514784,8.136843,26.482990,0.918255,0.031125,29.1,11.2,4.360000,34.0
51,6103,Tehama,0.465160,0.511675,0.155053,53654.0,3.360351,9.966781,19.090176,1.145318,NaN,35.1,11.1,NaN,39.8
52,6105,Trinity,0.818599,0.491159,0.573019,45508.0,3.641630,7.665814,17.603451,1.510479,NaN,30.0,9.8,NaN,19.9
53,6107,Tulare,0.373389,0.614492,0.238969,57398.0,1.072866,4.916412,11.175652,0.950478,0.021337,35.7,13.9,3.795082,32.1
54,6109,Tuolumne,0.311841,0.476933,0.275154,61396.0,2.686450,6.160719,27.833937,0.763734,NaN,28.0,8.9,NaN,31.9
55,6111,Ventura,0.222252,0.772534,0.207990,95819.0,0.526427,2.309816,14.892350,0.564127,0.019016,27.5,9.6,4.382199,34.7
56,6113,Yolo,0.236656,0.709969,0.186594,76247.0,0.463608,2.884491,13.680482,0.741454,0.027306,29.9,10.4,4.425532,33.5
57,6115,Yuba,0.311876,0.399202,0.149701,60764.0,2.630084,10.882041,21.463261,1.015850,NaN,31.3,10.6,NaN,38.9

In [ ]:
df_final.to_csv('datasci112_final.csv', index=False)
from google.colab import files
files.download('datasci112_final.csv')