In [ ]:
#clean food data set
import pandas as pd
df = pd.read_csv("StateAndCountyData.csv", header=None,
                 names=["FIPS", "State", "County", "Variable", "Value"],
                 dtype={"FIPS": str})
df_ca = df[df["State"] == "CA"]
variables = ["PCT_LACCESS_POP19", "MEDHHINC21", "FFRPTH20"]
df_ca_filtered = df_ca[df_ca["Variable"].isin(variables)]
df_food = df_ca_filtered.pivot(index=["FIPS", "County"],
                                columns="Variable",
                                values="Value").reset_index()
df_food.columns.name = None
df_food[variables] = df_food[variables].astype(float)
df_food = df_food.sort_values("County").reset_index(drop=True)

/tmp/ipykernel_184/3062521547.py:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("StateAndCountyData.csv", header=None,

In [ ]:
#clean health data set
file = "CountyHealthRankings.xlsx"
df_rank = pd.read_excel(
    file,
    sheet_name="Ranked Measure Data",
    header=1
)
df_add = pd.read_excel(
    file,
    sheet_name="Additional Measure Data",
    header=1
)
df_obesity = df_rank[["FIPS", "County", "% Adults with Obesity"]]
df_diabetes = df_add[["FIPS", "County", "% Adults with Diabetes"]]
df_obesity["FIPS"] = df_obesity["FIPS"].astype(str).str.zfill(5)
df_diabetes["FIPS"] = df_diabetes["FIPS"].astype(str).str.zfill(5)
df_health = pd.merge(
    df_obesity,
    df_diabetes[["FIPS", "% Adults with Diabetes"]],
    on="FIPS",
    how="inner")
df_health

/tmp/ipykernel_184/1834040534.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_obesity["FIPS"] = df_obesity["FIPS"].astype(str).str.zfill(5)
/tmp/ipykernel_184/1834040534.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_diabetes["FIPS"] = df_diabetes["FIPS"].astype(str).str.zfill(5)

     FIPS           County  % Adults with Obesity  % Adults with Diabetes
0   06000              NaN                   26.2                     9.4
1   06001          Alameda                   23.5                     9.1
2   06003           Alpine                   29.9                     9.9
3   06005           Amador                   29.4                     9.0
4   06007            Butte                   31.7                     9.5
5   06009        Calaveras                   30.1                     8.7
6   06011           Colusa                   32.3                    11.8
7   06013     Contra Costa                   23.9                     9.4
8   06015        Del Norte                   33.4                    10.9
9   06017        El Dorado                   26.0                     7.9
10  06019           Fresno                   37.6                    13.5
11  06021            Glenn                   32.3                    11.6
12  06023         Humboldt                   28.0                     9.5
13  06025         Imperial                   35.9                    14.6
14  06027             Inyo                   28.0                     9.2
15  06029             Kern                   35.5                    13.0
16  06031            Kings                   35.3                    12.9
17  06033             Lake                   32.3                    10.5
18  06035           Lassen                   30.6                    10.3
19  06037      Los Angeles                   27.8                    11.1
20  06039           Madera                   32.7                    12.7
21  06041            Marin                   22.5                     7.1
22  06043         Mariposa                   27.7                     9.0
23  06045        Mendocino                   30.8                    10.0
24  06047           Merced                   34.6                    13.2
25  06049            Modoc                   31.2                    10.2
26  06051             Mono                   29.0                     9.1
27  06053         Monterey                   32.1                    11.6
28  06055             Napa                   28.6                     9.1
29  06057           Nevada                   25.1                     7.8
30  06059           Orange                   24.5                    10.2
31  06061           Placer                   24.6                     7.6
32  06063           Plumas                   28.9                     8.3
33  06065        Riverside                   33.4                    11.1
34  06067       Sacramento                   27.8                    10.3
35  06069       San Benito                   30.1                    10.9
36  06071   San Bernardino                   33.3                    11.9
37  06073        San Diego                   24.1                     9.4
38  06075    San Francisco                   16.4                     9.0
39  06077      San Joaquin                   31.9                    11.5
40  06079  San Luis Obispo                   26.2                     8.7
41  06081        San Mateo                   20.6                     8.7
42  06083    Santa Barbara                   27.3                    10.3
43  06085      Santa Clara                   21.3                     9.0
44  06087       Santa Cruz                   29.3                     9.4
45  06089           Shasta                   27.8                     8.9
46  06091           Sierra                   29.6                     9.3
47  06093         Siskiyou                   31.3                     9.7
48  06095           Solano                   30.7                    10.0
49  06097           Sonoma                   27.1                     8.2
50  06099       Stanislaus                   30.8                    11.8
51  06101           Sutter                   29.1                    11.2
52  06103           Tehama                   35.1                    11.1
53  06105          Trinity                   30.0                     9.8
54  06107           Tulare                   35.7                    13.9
55  06109         Tuolumne                   28.0                     8.9
56  06111          Ventura                   27.5                     9.6
57  06113             Yolo                   29.9                    10.4
58  06115             Yuba                   31.3                    10.6

In [ ]:
#merge
import numpy as np
df_final = pd.merge(df_food, df_health, on=["FIPS", "County"])
df_final = df_final.rename(columns={
    "PCT_LACCESS_POP19": "% Population with low access to store",
    "FFRPTH20": "Fast-food restaurants/1,000 population",
    "MEDHHINC21": "Median household income"
})
df_final["Fast-food restaurants/1,000 population"] = (
    df_final["Fast-food restaurants/1,000 population"]
    .replace(-9999.0, np.nan)
)
df_final

,FIPS,County,"Fast-food restaurants/1,000 population",Median household income,% Population with low access to store,% Adults with Obesity,% Adults with Diabetes
0,06001,Alameda,0.827156,108971.0,8.083675,23.5,9.1
1,06003,Alpine,2.680965,87570.0,56.969242,29.9,9.9
2,06005,Amador,0.573809,68159.0,0.174187,29.4,9.0
3,06007,Butte,0.737976,62982.0,19.113434,31.7,9.5
4,06009,Calaveras,0.604647,68298.0,14.736117,30.1,8.7
5,06011,Colusa,0.417478,60725.0,39.329746,32.3,11.8
6,06013,Contra Costa,0.678623,110595.0,23.228312,23.9,9.4
7,06015,Del Norte,0.321796,48108.0,34.407192,33.4,10.9
8,06017,El Dorado,0.673837,87689.0,25.222891,26.0,7.9
9,06019,Fresno,0.731329,63140.0,13.327069,37.6,13.5
10,06021,Glenn,0.671782,56741.0,23.445011,32.3,11.6
11,06023,Humboldt,0.622328,53924.0,11.186273,28.0,9.5
12,06025,Imperial,0.610206,50970.0,17.641117,35.9,14.6
13,06027,Inyo,0.997451,62381.0,28.887903,28.0,9.2
14,06029,Kern,0.726678,57926.0,23.772337,35.5,13.0
15,06031,Kings,0.674561,60810.0,33.028690,35.3,12.9
16,06033,Lake,0.542812,55801.0,4.177565,32.3,10.5
17,06035,Lassen,0.533049,56923.0,31.891712,30.6,10.3
18,06037,Los Angeles,0.879006,77356.0,6.531888,27.8,11.1
19,06039,Madera,0.507096,60241.0,14.494282,32.7,12.7
20,06041,Marin,0.773320,118472.0,11.887547,22.5,7.1
21,06043,Mariposa,0.349650,60377.0,8.073803,27.7,9.0
22,06045,Mendocino,0.720419,57516.0,14.481230,30.8,10.0
23,06047,Merced,0.529987,54703.0,18.937424,34.6,13.2
24,06049,Modoc,NaN,49273.0,40.543320,31.2,10.2
25,06051,Mono,1.651300,70945.0,57.093903,29.0,9.1
26,06053,Monterey,0.666039,81404.0,16.629837,32.1,11.6
27,06055,Napa,0.566322,94127.0,12.084171,28.6,9.1
28,06057,Nevada,0.622452,77220.0,34.762379,25.1,7.8
29,06059,Orange,0.970047,100210.0,8.671787,24.5,10.2
30,06061,Placer,0.878521,103588.0,31.929096,24.6,7.6
31,06063,Plumas,0.579955,58154.0,6.298171,28.9,8.3
32,06065,Riverside,0.696211,78690.0,24.481379,33.4,11.1
33,06067,Sacramento,0.772218,79611.0,16.813540,27.8,10.3
34,06069,San Benito,0.515182,95187.0,17.873438,30.1,10.9
35,06071,San Bernardino,0.773348,74218.0,24.656145,33.3,11.9
36,06073,San Diego,0.853432,90756.0,14.927285,24.1,9.4
37,06075,San Francisco,1.152773,119776.0,0.584508,16.4,9.0
38,06077,San Joaquin,0.658882,79598.0,14.412910,31.9,11.5
39,06079,San Luis Obispo,0.924715,79688.0,18.622091,26.2,8.7
40,06081,San Mateo,0.767498,131151.0,10.517214,20.6,8.7
41,06083,Santa Barbara,0.847637,83185.0,12.243940,27.3,10.3
42,06085,Santa Clara,0.798068,141161.0,8.487587,21.3,9.0
43,06087,Santa Cruz,0.696490,90370.0,22.582853,29.3,9.4
44,06089,Shasta,0.714976,60187.0,20.261036,27.8,8.9
45,06091,Sierra,NaN,60659.0,88.249901,29.6,9.3
46,06093,Siskiyou,0.716846,50069.0,28.644606,31.3,9.7
47,06095,Solano,0.660051,87348.0,21.658522,30.7,10.0
48,06097,Sonoma,0.645136,92999.0,13.296393,27.1,8.2
49,06099,Stanislaus,0.707169,73151.0,9.670941,30.8,11.8
50,06101,Sutter,0.664004,63246.0,26.482990,29.1,11.2
51,06103,Tehama,0.511675,53654.0,19.090176,35.1,11.1
52,06105,Trinity,0.491159,45508.0,17.603451,30.0,9.8
53,06107,Tulare,0.614492,57398.0,11.175652,35.7,13.9
54,06109,Tuolumne,0.476933,61396.0,27.833937,28.0,8.9
55,06111,Ventura,0.772534,95819.0,14.892350,27.5,9.6
56,06113,Yolo,0.709969,76247.0,13.680482,29.9,10.4
57,06115,Yuba,0.399202,60764.0,21.463261,31.3,10.6

In [ ]:
df_final.to_csv('datasci112_final.csv', index=False)
from google.colab import files
files.download('datasci112_final.csv')