## Setup

In [23]:
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import KFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from patsy import dmatrices

In [24]:
df = pd.read_csv('/Users/emmiekao/Downloads/datasci112_final (1).csv')

In [25]:
df

,FIPS,County,"Convenience stores/1,000 population","Fast-food restaurants/1,000 population","Grocery stores/1,000 population",Median household income,"% Households, no car & low access to store",% Population low income & low access to store,% Population with low access to store,"SNAP-authorized stores/1,000 population","Supercenters/1,000 population",% Adults with Obesity,% Adults with Diabetes,Retail Food Environment Index,Cancer Incidence Rate
0,6001,Alameda,0.197314,0.827156,0.219572,108971.0,0.342808,1.117399,8.083675,0.545731,0.016242,23.5,9.1,4.344388,31.7
1,6003,Alpine,NaN,2.680965,NaN,87570.0,6.022490,16.785139,56.969242,NaN,NaN,29.9,9.9,NaN,NaN
2,6005,Amador,0.324327,0.573809,0.299379,68159.0,3.163143,0.095632,0.174187,0.763980,NaN,29.4,9.0,NaN,39.3
3,6007,Butte,0.329034,0.737976,0.188019,62982.0,1.979342,6.450867,19.113434,0.926945,0.018802,31.7,9.5,5.159091,42.5
4,6009,Calaveras,0.410296,0.604647,0.259135,68298.0,1.547478,5.989503,14.736117,0.985243,NaN,30.1,8.7,NaN,38.4
5,6011,Colusa,0.556638,0.417478,0.324705,60725.0,2.258987,12.356255,39.329746,1.283756,NaN,32.3,11.8,NaN,40.1
6,6013,Contra Costa,0.200463,0.678623,0.194388,110595.0,0.766959,2.867471,23.228312,0.542727,0.013885,23.9,9.4,4.220833,34.2
7,6015,Del Norte,0.178776,0.321796,0.143021,48108.0,3.967303,14.445117,34.407192,0.983177,NaN,33.4,10.9,NaN,24.5
8,6017,El Dorado,0.285085,0.673837,0.171051,87689.0,1.906889,4.258567,25.222891,0.636368,0.020733,26.0,7.9,5.000000,35.6
9,6019,Fresno,0.298726,0.731329,0.252768,63140.0,0.889459,5.349311,13.327069,0.916412,0.019982,37.6,13.5,3.776557,33.1
10,6021,Glenn,0.388926,0.671782,0.212142,56741.0,2.142960,8.745303,23.445011,1.256238,NaN,32.3,11.6,NaN,34.8
11,6023,Humboldt,0.422294,0.622328,0.296347,53924.0,1.848892,4.540260,11.186273,1.072488,0.029635,28.0,9.5,3.204545,36.4
12,6025,Imperial,0.410502,0.610206,0.138683,50970.0,1.431648,7.648736,17.641117,0.729488,0.027737,35.9,14.6,6.133333,34.8
13,6027,Inyo,0.831209,0.997451,0.221656,62381.0,1.883897,7.771645,28.887903,1.168410,NaN,28.0,9.2,NaN,30.7
14,6029,Kern,0.306203,0.726678,0.211902,57926.0,1.337915,7.829901,23.772337,0.860089,0.017751,35.5,13.0,4.497585,36.1
15,6031,Kings,0.340555,0.674561,0.255416,60810.0,1.055195,6.822826,33.028690,0.767138,0.019647,35.3,12.9,3.690476,27.6
16,6033,Lake,0.480777,0.542812,0.372214,55801.0,2.951067,1.889676,4.177565,1.058450,NaN,32.3,10.5,NaN,39.6
17,6035,Lassen,0.433102,0.533049,0.233209,56923.0,1.978429,9.301450,31.891712,1.035359,NaN,30.6,10.3,NaN,30.5
18,6037,Los Angeles,0.216232,0.879006,0.191893,77356.0,0.230622,1.452951,6.531888,0.633611,0.016092,27.8,11.1,5.265957,34.7
19,6039,Madera,0.373983,0.507096,0.171145,60241.0,2.185023,5.418890,14.494282,0.966657,NaN,32.7,12.7,NaN,35.6
20,6041,Marin,0.190416,0.773320,0.291452,118472.0,0.366653,1.165825,11.887547,0.456840,0.015544,22.5,7.1,3.139241,33.1
21,6043,Mariposa,0.174825,0.349650,0.291375,60377.0,2.170580,2.611354,8.073803,0.817280,NaN,27.7,9.0,NaN,34.0
22,6045,Mendocino,0.476406,0.720419,0.476406,57516.0,1.994999,5.922134,14.481230,1.108124,NaN,30.8,10.0,NaN,35.3
23,6047,Merced,0.272156,0.529987,0.196955,54703.0,1.438985,7.711543,18.937424,0.921039,0.025067,34.6,13.2,3.612903,39.4
24,6049,Modoc,0.342349,NaN,0.570581,49273.0,0.848351,17.175961,40.543320,1.618310,NaN,31.2,10.2,NaN,36.8
25,6051,Mono,0.550433,1.651300,0.412825,70945.0,1.467635,17.237467,57.093903,0.680838,NaN,29.0,9.1,NaN,31.2
26,6053,Monterey,0.297049,0.666039,0.280804,81404.0,0.648934,5.080918,16.629837,0.664977,0.018566,32.1,11.6,3.217054,30.7
27,6055,Napa,0.338322,0.566322,0.272129,94127.0,0.910559,2.629963,12.084171,0.524078,0.029419,28.6,9.1,3.000000,35.4
28,6057,Nevada,0.281108,0.622452,0.291147,77220.0,1.389410,8.613041,34.762379,0.674342,NaN,25.1,7.8,NaN,24.6
29,6059,Orange,0.222618,0.970047,0.160727,100210.0,0.262204,1.121259,8.671787,0.483745,0.023683,24.5,10.2,6.467465,32.0
30,6061,Placer,0.307730,0.878521,0.161310,103588.0,1.167848,5.106532,31.929096,0.543521,0.024817,24.6,7.6,6.373334,32.1
31,6063,Plumas,0.579955,0.579955,0.579955,58154.0,1.802116,1.071077,6.298171,1.272265,NaN,28.9,8.3,NaN,29.7
32,6065,Riverside,0.217340,0.696211,0.141813,78690.0,0.990094,6.965470,24.481379,0.555261,0.018480,33.4,11.1,5.699248,35.0
33,6067,Sacramento,0.243723,0.772218,0.188565,79611.0,0.658604,4.226967,16.813540,0.686419,0.021807,27.8,10.3,4.829268,35.5
34,6069,San Benito,0.234174,0.515182,0.140504,95187.0,0.896890,2.696964,17.873438,0.370639,NaN,30.1,10.9,NaN,40.3
35,6071,San Bernardino,0.252149,0.773348,0.140692,74218.0,1.342740,8.528562,24.656145,0.692940,0.018272,33.3,11.9,6.451149,36.0
36,6073,San Diego,0.223561,0.853432,0.173147,90756.0,0.476854,2.763061,14.927285,0.541995,0.019505,24.1,9.4,5.590343,34.2
37,6075,San Francisco,0.129240,1.152773,0.400413,119776.0,0.114791,0.302544,0.584508,0.627470,0.010385,16.4,9.0,3.120787,32.3
38,6077,San Joaquin,0.260428,0.658882,0.239594,79598.0,0.871344,4.535321,14.412910,0.762081,0.019532,31.9,11.5,3.547739,37.2
39,6079,San Luis Obispo,0.294067,0.924715,0.212578,79688.0,1.019286,4.054190,18.622091,0.653149,0.017715,26.2,8.7,5.292308,33.3
40,6081,San Mateo,0.195171,0.767498,0.238689,131151.0,0.361650,0.919327,10.517214,0.405701,0.097586,20.6,8.7,2.862745,30.4
41,6083,Santa Barbara,0.233831,0.847637,0.278798,83185.0,0.541791,2.881691,12.243940,0.597467,0.015739,27.3,10.3,3.671756,34.2
42,6085,Santa Clara,0.191390,0.798068,0.175135,141161.0,0.298099,0.966271,8.487587,0.426224,0.018352,21.3,9.0,5.113821,33.2
43,6087,Santa Cruz,0.218579,0.696490,0.240808,90370.0,0.974291,5.418862,22.582853,0.592022,0.014819,29.3,9.4,3.579710,37.7
44,6089,Shasta,0.441274,0.714976,0.229016,60187.0,2.143146,6.916362,20.261036,1.000814,0.022343,27.8,8.9,4.600000,37.9
45,6091,Sierra,1.027397,NaN,NaN,60659.0,4.103383,24.821465,88.249901,1.028807,NaN,29.6,9.3,NaN,NaN
46,6093,Siskiyou,0.578102,0.716846,0.323737,50069.0,2.898830,11.382891,28.644606,1.634543,NaN,31.3,9.7,NaN,32.3
47,6095,Solano,0.295345,0.660051,0.163335,87348.0,0.626808,3.780611,21.658522,0.596459,0.024612,30.7,10.0,5.083333,35.5
48,6097,Sonoma,0.293986,0.645136,0.287861,92999.0,0.805661,2.581933,13.296393,0.692005,0.016333,27.1,8.2,3.087248,36.9
49,6099,Stanislaus,0.332678,0.707169,0.225421,73151.0,0.743791,3.369372,9.670941,0.880334,0.021815,30.8,11.8,4.205882,35.6
50,6101,Sutter,0.466878,0.664004,0.228251,63246.0,1.514784,8.136843,26.482990,0.918255,0.031125,29.1,11.2,4.360000,34.0
51,6103,Tehama,0.465160,0.511675,0.155053,53654.0,3.360351,9.966781,19.090176,1.145318,NaN,35.1,11.1,NaN,39.8
52,6105,Trinity,0.818599,0.491159,0.573019,45508.0,3.641630,7.665814,17.603451,1.510479,NaN,30.0,9.8,NaN,19.9
53,6107,Tulare,0.373389,0.614492,0.238969,57398.0,1.072866,4.916412,11.175652,0.950478,0.021337,35.7,13.9,3.795082,32.1
54,6109,Tuolumne,0.311841,0.476933,0.275154,61396.0,2.686450,6.160719,27.833937,0.763734,NaN,28.0,8.9,NaN,31.9
55,6111,Ventura,0.222252,0.772534,0.207990,95819.0,0.526427,2.309816,14.892350,0.564127,0.019016,27.5,9.6,4.382199,34.7
56,6113,Yolo,0.236656,0.709969,0.186594,76247.0,0.463608,2.884491,13.680482,0.741454,0.027306,29.9,10.4,4.425532,33.5
57,6115,Yuba,0.311876,0.399202,0.149701,60764.0,2.630084,10.882041,21.463261,1.015850,NaN,31.3,10.6,NaN,38.9

## Prep dataframe

Rename columns

In [26]:
df.columns = df.columns.str.strip()

rename_map = {
    "Retail Food Environment Index": "rfei",
    "Median household income": "income",
    "% Adults with Obesity": "obesity",
    "% Adults with Diabetes": "diabetes",
    "Cancer Incidence Rate": "cancer",
    "% Households, no car & low access to store": "no_car_low_access",
    "% Population low income & low access to store": "low_income_low_access",
    "% Population with low access to store": "low_access",
    "Convenience stores/1,000 population": "convenience",
    "Fast-food restaurants/1,000 population": "fast_food",
    "Grocery stores/1,000 population": "grocery",
    "SNAP-authorized stores/1,000 population": "snap",
    "Supercenters/1,000 population": "supercenters"
}

df = df.rename(columns=rename_map)

needed = [
    "income", "rfei",
    "no_car_low_access", "low_income_low_access", "low_access",
    "convenience", "fast_food", "grocery", "snap", "supercenters",
    "obesity", "diabetes", "cancer"
]

df = df[needed].apply(pd.to_numeric, errors="coerce").dropna().copy()

There are two categories of variable in our dataset: `access` variables (describing food accessibility in a county) and `store` variables (describing the amount of stores in a county). 

We will attempt two strategies to create linear regressions. The first is simply using all variables as individuals, and the second is Principle Component Analysis (PCA), where we condense each group of variables into one while attempting to retain the most important information.

Below, we create these condensed variables.

In [27]:
access_vars = ["no_car_low_access", "low_income_low_access", "low_access"]
store_vars = ["convenience", "fast_food", "grocery", "snap", "supercenters"]
all_non_rfei_vars = access_vars + store_vars

def make_pc1(data, cols, new_name):
    scaler = StandardScaler()
    Z = scaler.fit_transform(data[cols])

    pca = PCA(n_components=1)
    pc1 = pca.fit_transform(Z).ravel()

    loadings = pd.Series(pca.components_[0], index=cols)

    if loadings.mean() < 0:
        pc1 *= -1
        loadings *= -1

    out = {
        "scores": pc1,
        "explained_variance": pca.explained_variance_ratio_[0],
        "loadings": loadings.sort_values()
    }
    return out

access_info = make_pc1(df, access_vars, "access_pc1")
store_info = make_pc1(df, store_vars, "store_pc1")
combined_info = make_pc1(df, all_non_rfei_vars, "combined_pc1")

df["access_pc1"] = access_info["scores"]
df["store_pc1"] = store_info["scores"]
df["combined_pc1"] = combined_info["scores"]

print("Access PC1 explained variance:", access_info["explained_variance"])
print(access_info["loadings"], "\n")

print("Store PC1 explained variance:", store_info["explained_variance"])
print(store_info["loadings"], "\n")

print("Combined PC1 explained variance:", combined_info["explained_variance"])
print(combined_info["loadings"])

Access PC1 explained variance: 0.7950938869810505
low_access               0.553703
no_car_low_access        0.568862
low_income_low_access    0.608120
dtype: float64

Store PC1 explained variance: 0.42895670764654803
fast_food      -0.519114
grocery        -0.025683
supercenters    0.025955
snap            0.581756
convenience     0.625098
dtype: float64

Combined PC1 explained variance: 0.4878298090423431
fast_food               -0.344809
grocery                 -0.138636
supercenters            -0.020501
low_access               0.343684
snap                     0.375504
convenience              0.425898
no_car_low_access        0.458577
low_income_low_access    0.458979
dtype: float64

## Helper functions and formulas

Create helper functions for models

In [28]:
def cv_rmse(formula, data, n_splits=5):
    y, X = dmatrices(formula, data=data, return_type="dataframe")
    y = np.ravel(y)

    pipe = Pipeline([
        ("scale", StandardScaler(with_mean=False)),
        ("lr", LinearRegression())
    ])

    cv = KFold(n_splits=n_splits, shuffle=True, random_state=42)
    scores = cross_val_score(
        pipe,
        X,
        y,
        cv=cv,
        scoring="neg_root_mean_squared_error"
    )
    return -scores.mean()

def partial_r2(reduced_model, full_model):
    return (full_model.rsquared - reduced_model.rsquared) / (1 - reduced_model.rsquared)

def fit_formula(formula, data):
    return smf.ols(formula, data=data).fit()

We want to test essentially all possible outcomes. We use `income` as a baseline, since we know that it is already strongly correlated with the health outcomes.

In [29]:
outcomes = ["obesity", "diabetes", "cancer"]

def get_formulas(y):
    formulas = {
        "baseline": f"{y} ~ income",

        "rfei_linear": f"{y} ~ rfei",
        "rfei_quadratic": f"{y} ~ rfei + I(rfei**2)",

        "access_only_pc": f"{y} ~ access_pc1",
        "store_only_pc": f"{y} ~ store_pc1",
        "combined_only_pc": f"{y} ~ combined_pc1",

        "rfei_plus_access_linear": f"{y} ~ access_pc1 + rfei",
        "rfei_plus_access_quadratic": f"{y} ~ access_pc1 + rfei + I(rfei**2)",

        "rfei_plus_store_linear": f"{y} ~ store_pc1 + rfei",
        "rfei_plus_store_quadratic": f"{y} ~ store_pc1 + rfei + I(rfei**2)",

        "controls_separate_pc": f"{y} ~ access_pc1 + store_pc1",
        "rfei_plus_separate_linear": f"{y} ~ access_pc1 + store_pc1 + rfei",
        "rfei_plus_separate_quadratic": f"{y} ~ access_pc1 + store_pc1 + rfei + I(rfei**2)",

        "rfei_plus_combined_linear": f"{y} ~ combined_pc1 + rfei",
        "rfei_plus_combined_quadratic": f"{y} ~ combined_pc1 + rfei + I(rfei**2)",

        "raw_access": f"{y} ~ no_car_low_access + low_income_low_access + low_access",
        "raw_store": f"{y} ~ convenience + fast_food + grocery + snap + supercenters",
        "raw_all": f"{y} ~ no_car_low_access + low_income_low_access + low_access + convenience + fast_food + grocery + snap + supercenters"
    }
    return formulas

## Fit Models and Assess

In [48]:
results = []
models = {}

for y in outcomes:
    formulas = get_formulas(y)
    fitted = {}

    for model_name, formula in formulas.items():
        model = fit_formula(formula, df)
        fitted[model_name] = model
        models[(y, model_name)] = model

        results.append({
            "outcome": y,
            "model": model_name,
            "formula": formula,
            "n_params": int(model.df_model + 1),
            "r2": model.rsquared,
            "cv_rmse": cv_rmse(formula, df)
        })

results_df = pd.DataFrame(results)
results_df.head()

,outcome,model,formula,n_params,r2,cv_rmse
0,obesity,baseline,obesity ~ income,2,0.696579,2.870767
1,obesity,rfei_linear,obesity ~ rfei,2,0.006371,5.119239
2,obesity,rfei_quadratic,obesity ~ rfei + I(rfei**2),3,0.039556,5.043944
3,obesity,access_only_pc,obesity ~ access_pc1,2,0.388775,4.219348
4,obesity,store_only_pc,obesity ~ store_pc1,2,0.483721,3.969381

In [49]:
results_df.to_csv("full_model_results.csv") # for visualizations

### Compare models

In [35]:
# best by CV RMSE within each outcome
best_by_rmse = (
    results_df
    .sort_values(["outcome", "cv_rmse", "r2"], ascending=[True, True, False])
    .groupby("outcome", as_index=False)
    .head(8)
)

best_by_rmse[["outcome", "model", "r2", "cv_rmse"]]

     outcome                         model        r2   cv_rmse
51    cancer                    raw_access  0.372482  2.384731
41    cancer              combined_only_pc  0.171439  2.468861
40    cancer                 store_only_pc  0.133940  2.470346
46    cancer          controls_separate_pc  0.157381  2.507929
36    cancer                      baseline  0.131084  2.556303
39    cancer                access_only_pc  0.131951  2.583162
50    cancer  rfei_plus_combined_quadratic  0.193229  2.674513
49    cancer     rfei_plus_combined_linear  0.172236  2.711230
33  diabetes                    raw_access  0.707878  1.146671
18  diabetes                      baseline  0.465824  1.462990
35  diabetes                       raw_all  0.797597  1.508448
26  diabetes        rfei_plus_store_linear  0.253411  1.774558
22  diabetes                 store_only_pc  0.235199  1.775419
29  diabetes     rfei_plus_separate_linear  0.262066  1.778697
28  diabetes          controls_separate_pc  0.235393  1.781403
23  diabetes              combined_only_pc  0.192853  1.792805
0    obesity                      baseline  0.696579  2.870767
17   obesity                       raw_all  0.835772  3.240952
15   obesity                    raw_access  0.673942  3.256631
5    obesity              combined_only_pc  0.519544  3.786437
10   obesity          controls_separate_pc  0.523210  3.846759
13   obesity     rfei_plus_combined_linear  0.519788  3.942695
4    obesity                 store_only_pc  0.483721  3.969381
11   obesity     rfei_plus_separate_linear  0.531359  3.981178

In [36]:
# best by adjusted R^2 within each outcome
best_by_r2 = (
    results_df
    .sort_values(["outcome", "r2", "cv_rmse"], ascending=[True, False, True])
    .groupby("outcome", as_index=False)
    .head(8)
)

best_by_r2[["outcome", "model", "r2", "cv_rmse"]]

     outcome                         model        r2   cv_rmse
53    cancer                       raw_all  0.605732  2.801748
51    cancer                    raw_access  0.372482  2.384731
52    cancer                     raw_store  0.327636  2.719932
50    cancer  rfei_plus_combined_quadratic  0.193229  2.674513
48    cancer  rfei_plus_separate_quadratic  0.183641  2.805844
49    cancer     rfei_plus_combined_linear  0.172236  2.711230
45    cancer     rfei_plus_store_quadratic  0.172038  2.732678
41    cancer              combined_only_pc  0.171439  2.468861
35  diabetes                       raw_all  0.797597  1.508448
33  diabetes                    raw_access  0.707878  1.146671
18  diabetes                      baseline  0.465824  1.462990
34  diabetes                     raw_store  0.360862  1.901009
30  diabetes  rfei_plus_separate_quadratic  0.262112  1.883042
29  diabetes     rfei_plus_separate_linear  0.262066  1.778697
27  diabetes     rfei_plus_store_quadratic  0.253553  1.882374
26  diabetes        rfei_plus_store_linear  0.253411  1.774558
17   obesity                       raw_all  0.835772  3.240952
0    obesity                      baseline  0.696579  2.870767
15   obesity                    raw_access  0.673942  3.256631
16   obesity                     raw_store  0.645985  4.015784
12   obesity  rfei_plus_separate_quadratic  0.532252  4.036089
11   obesity     rfei_plus_separate_linear  0.531359  3.981178
10   obesity          controls_separate_pc  0.523210  3.846759
14   obesity  rfei_plus_combined_quadratic  0.521317  3.992228

## Sort results by health outcome

In [37]:
obesity = results_df[results_df["outcome"]=="obesity"]

In [38]:
diabetes = results_df[results_df["outcome"]=="diabetes"]

In [39]:
cancer = results_df[results_df["outcome"]=="cancer"]

In [40]:
obesity = obesity.sort_values(by="r2", ascending=False)
obesity

,outcome,model,formula,n_params,r2,cv_rmse
17,obesity,raw_all,obesity ~ no_car_low_access + low_income_low_a...,9,0.835772,3.240952
0,obesity,baseline,obesity ~ income,2,0.696579,2.870767
15,obesity,raw_access,obesity ~ no_car_low_access + low_income_low_a...,4,0.673942,3.256631
16,obesity,raw_store,obesity ~ convenience + fast_food + grocery + ...,6,0.645985,4.015784
12,obesity,rfei_plus_separate_quadratic,obesity ~ access_pc1 + store_pc1 + rfei + I(rf...,5,0.532252,4.036089
11,obesity,rfei_plus_separate_linear,obesity ~ access_pc1 + store_pc1 + rfei,4,0.531359,3.981178
10,obesity,controls_separate_pc,obesity ~ access_pc1 + store_pc1,3,0.523210,3.846759
14,obesity,rfei_plus_combined_quadratic,obesity ~ combined_pc1 + rfei + I(rfei**2),4,0.521317,3.992228
13,obesity,rfei_plus_combined_linear,obesity ~ combined_pc1 + rfei,3,0.519788,3.942695
5,obesity,combined_only_pc,obesity ~ combined_pc1,2,0.519544,3.786437
9,obesity,rfei_plus_store_quadratic,obesity ~ store_pc1 + rfei + I(rfei**2),4,0.515525,4.091549
8,obesity,rfei_plus_store_linear,obesity ~ store_pc1 + rfei,3,0.515006,4.016958
4,obesity,store_only_pc,obesity ~ store_pc1,2,0.483721,3.969381
7,obesity,rfei_plus_access_quadratic,obesity ~ access_pc1 + rfei + I(rfei**2),4,0.405889,4.324153
6,obesity,rfei_plus_access_linear,obesity ~ access_pc1 + rfei,3,0.396140,4.317547
3,obesity,access_only_pc,obesity ~ access_pc1,2,0.388775,4.219348
2,obesity,rfei_quadratic,obesity ~ rfei + I(rfei**2),3,0.039556,5.043944
1,obesity,rfei_linear,obesity ~ rfei,2,0.006371,5.119239

In [41]:
diabetes = diabetes.sort_values(by="r2", ascending=False)
diabetes

,outcome,model,formula,n_params,r2,cv_rmse
35,diabetes,raw_all,diabetes ~ no_car_low_access + low_income_low_...,9,0.797597,1.508448
33,diabetes,raw_access,diabetes ~ no_car_low_access + low_income_low_...,4,0.707878,1.146671
18,diabetes,baseline,diabetes ~ income,2,0.465824,1.462990
34,diabetes,raw_store,diabetes ~ convenience + fast_food + grocery +...,6,0.360862,1.901009
30,diabetes,rfei_plus_separate_quadratic,diabetes ~ access_pc1 + store_pc1 + rfei + I(r...,5,0.262112,1.883042
29,diabetes,rfei_plus_separate_linear,diabetes ~ access_pc1 + store_pc1 + rfei,4,0.262066,1.778697
27,diabetes,rfei_plus_store_quadratic,diabetes ~ store_pc1 + rfei + I(rfei**2),4,0.253553,1.882374
26,diabetes,rfei_plus_store_linear,diabetes ~ store_pc1 + rfei,3,0.253411,1.774558
28,diabetes,controls_separate_pc,diabetes ~ access_pc1 + store_pc1,3,0.235393,1.781403
22,diabetes,store_only_pc,diabetes ~ store_pc1,2,0.235199,1.775419
32,diabetes,rfei_plus_combined_quadratic,diabetes ~ combined_pc1 + rfei + I(rfei**2),4,0.194315,1.942509
31,diabetes,rfei_plus_combined_linear,diabetes ~ combined_pc1 + rfei,3,0.192938,1.838403
23,diabetes,combined_only_pc,diabetes ~ combined_pc1,2,0.192853,1.792805
25,diabetes,rfei_plus_access_quadratic,diabetes ~ access_pc1 + rfei + I(rfei**2),4,0.112132,2.017584
24,diabetes,rfei_plus_access_linear,diabetes ~ access_pc1 + rfei,3,0.105518,1.929530
21,diabetes,access_only_pc,diabetes ~ access_pc1,2,0.105191,1.878189
20,diabetes,rfei_quadratic,diabetes ~ rfei + I(rfei**2),3,0.019766,2.033688
19,diabetes,rfei_linear,diabetes ~ rfei,2,0.004511,1.992230

In [42]:
cancer = cancer.sort_values(by="r2", ascending=False)
cancer

,outcome,model,formula,n_params,r2,cv_rmse
53,cancer,raw_all,cancer ~ no_car_low_access + low_income_low_ac...,9,0.605732,2.801748
51,cancer,raw_access,cancer ~ no_car_low_access + low_income_low_ac...,4,0.372482,2.384731
52,cancer,raw_store,cancer ~ convenience + fast_food + grocery + s...,6,0.327636,2.719932
50,cancer,rfei_plus_combined_quadratic,cancer ~ combined_pc1 + rfei + I(rfei**2),4,0.193229,2.674513
48,cancer,rfei_plus_separate_quadratic,cancer ~ access_pc1 + store_pc1 + rfei + I(rfe...,5,0.183641,2.805844
49,cancer,rfei_plus_combined_linear,cancer ~ combined_pc1 + rfei,3,0.172236,2.711230
45,cancer,rfei_plus_store_quadratic,cancer ~ store_pc1 + rfei + I(rfei**2),4,0.172038,2.732678
41,cancer,combined_only_pc,cancer ~ combined_pc1,2,0.171439,2.468861
43,cancer,rfei_plus_access_quadratic,cancer ~ access_pc1 + rfei + I(rfei**2),4,0.163580,2.735915
47,cancer,rfei_plus_separate_linear,cancer ~ access_pc1 + store_pc1 + rfei,4,0.161887,2.858335
46,cancer,controls_separate_pc,cancer ~ access_pc1 + store_pc1,3,0.157381,2.507929
44,cancer,rfei_plus_store_linear,cancer ~ store_pc1 + rfei,3,0.151943,2.741790
40,cancer,store_only_pc,cancer ~ store_pc1,2,0.133940,2.470346
42,cancer,rfei_plus_access_linear,cancer ~ access_pc1 + rfei,3,0.132107,2.830703
39,cancer,access_only_pc,cancer ~ access_pc1,2,0.131951,2.583162
36,cancer,baseline,cancer ~ income,2,0.131084,2.556303
38,cancer,rfei_quadratic,cancer ~ rfei + I(rfei**2),3,0.056835,2.918024
37,cancer,rfei_linear,cancer ~ rfei,2,0.006841,2.973417

## Train Models Based on SNAP

In [43]:
results = []
for y in outcomes:
    formulas = {
        "with_snap": f"{y} ~ convenience + fast_food + grocery + snap + supercenters",
        "without_snap": f"{y} ~ convenience + fast_food + grocery + supercenters"
    }

    for model_name, formula in formulas.items():
        model = fit_formula(formula, df)
        models[(y, model_name)] = model

        results.append({
            "outcome": y,
            "model": model_name,
            "formula": formula,
            "n_params": int(model.df_model + 1),
            "r2": model.rsquared,
            "cv_rmse": cv_rmse(formula, df)
        })

results_df = pd.DataFrame(results)
results_df[["outcome", "model", "r2", "cv_rmse"]]

    outcome         model        r2   cv_rmse
0   obesity     with_snap  0.645985  4.015784
1   obesity  without_snap  0.544610  3.983172
2  diabetes     with_snap  0.360862  1.901009
3  diabetes  without_snap  0.196291  2.016048
4    cancer     with_snap  0.327636  2.719932
5    cancer  without_snap  0.195412  3.006018

In [44]:
results_df.to_csv("store_snap.csv")

In [45]:
results = []
for y in outcomes:
    formulas = {
        "only_snap": f"{y} ~ snap",
        "only_rfei": f"{y} ~ rfei"
    }

    for model_name, formula in formulas.items():
        model = fit_formula(formula, df)
        models[(y, model_name)] = model

        results.append({
            "outcome": y,
            "model": model_name,
            "formula": formula,
            "n_params": int(model.df_model + 1),
            "r2": model.rsquared,
            "cv_rmse": cv_rmse(formula, df)
        })

results_df = pd.DataFrame(results)
results_df[["outcome", "model", "r2", "cv_rmse"]]

    outcome      model        r2   cv_rmse
0   obesity  only_snap  0.369309  4.199055
1   obesity  only_rfei  0.006371  5.119239
2  diabetes  only_snap  0.262451  1.814165
3  diabetes  only_rfei  0.004511  1.992230
4    cancer  only_snap  0.167077  2.515679
5    cancer  only_rfei  0.006841  2.973417

In [46]:
results_df.to_csv("only_snap.csv")